### ISSUE TITLE
Latest update badly broken

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#59]
been fine for  ages but after latest pull:
on startup after the "header" you added....

`Running as user: docker
chown: changing ownership of '/steamcmd/rust/rust.env': Operation not permitted
chown: changing ownership of '/steamcmd/rust/steamapps/libraryfolders.vdf': Operation not permitted
chown: changing ownership of '/steamcmd/rust/steamapps/shadercache': Operation not permitted
chown: changing ownership of '/steamcmd/rust/steamapps/appmanifest_258550.acf': Operation not permitted`

for every file in the container

until:

`Waiting for user info...OK
force_install_dir /steamcmd/rust
app_info_update 1
app_update 258550 validate
 Update state (0x0) : Timed out waiting for update to start, bailing.
Error! App '258550' state is 0x204 after update job.
quit
applicationmanager.cpp (927) : Assertion Failed: m_bStateChangesSavedToDisk
Downloading and installing latest Oxide..
x RustDedicated_Data/: Can't restore time
x RustDedicated_Data/Managed/: Can't restore time
x RustDedicated_Data/Managed/Assembly-CSharp.dll: Can't unlink already-existing object
x RustDedicated_Data/Managed/Facepunch.Console.dll: Can't unlink already-existing object
x RustDedicated_Data/Managed/Facepunch.Network.dll: Can't unlink already-existing object
x RustDedicated_Data/Managed/Facepunch.Rcon.dll: Can't unlink already-existing object
x RustDedicated_Data/Managed/Mono.Data.Tds.dll: Can't unlink already-existing object
x RustDedicated_Data/Managed/MySql.Data.dll: Can't unlink already-existing object
x RustDedicated_Data/Managed/NewAssembly.dll: Can't unlink already-existing object
.........

x RustDedicated_Data/Managed/x86/sqlite3.dll: Can't unlink already-existing object
bsdtar: Error exit delayed from previous errors.
chmod: cannot access '/steamcmd/rust/CSharpCompiler.x86_x64': No such file or directory
chmod: changing permissions of '/dev/null': Operation not permitted
Starting web server..
Log rotation disabled!
Starting Rust..
Found path: /steamcmd/rust/RustDedicated
Unable to open log file, exiting.
Exiting..
`

*******Then after   deleting container and trying a clean "restart" of docker********

`Listening for IPv4 broadcast on: 27036
Logged in OK
Waiting for user info...OK
force_install_dir /steamcmd/rust
app_info_update 1
app_update 258550 validate
 Update state (0x0) : Timed out waiting for update to start, bailing.
Error! App '258550' state is 0x204 after update job.
quit
applicationmanager.cpp (927) : Assertion Failed: m_bStateChangesSavedToDisk
Downloading and installing latest Oxide..
x RustDedicated_Data/: Can't restore time
x RustDedicated_Data/Managed/: Can't restore time
x RustDedicated_Data/Managed/Assembly-CSharp.dll: Can't unlink already-existing object
.....

x RustDedicated_Data/Managed/x86/libsqlite3.so: Can't unlink already-existing object
x RustDedicated_Data/Managed/x86/mono-2.0.dll: Can't unlink already-existing object
x RustDedicated_Data/Managed/x86/msvcp140.dll: Can't unlink already-existing object
x RustDedicated_Data/Managed/x86/msvcr120.dll: Can't unlink already-existing object
x RustDedicated_Data/Managed/x86/sqlite3.dll: Can't unlink already-existing object
bsdtar: Error exit delayed from previous errors.
chmod: cannot access '/steamcmd/rust/CSharpCompiler.x86_x64': No such file or directory
chmod: changing permissions of '/dev/null': Operation not permitted
Starting web server..
Log rotation disabled!
Starting Rust..
Found path: /steamcmd/rust/RustDedicated
Unable to open log file, exiting.
Exiting..`

**Comment by Dids** [comment]
Since it's now running as a non-root user by default, volume permissions should be adjusted to reflect this. Stop your container and run `chown -R 1000:1000 /path/to/your/volume` and it should work fine.

**Comment by Hardcore-fs** [comment]
ah.... perhaps a note or something in the header....
since it just updates , without any warnings.... or notes...

`chown -R 1000:1000 /path/to/your/mapped_container_volume`

also i'm seeing this:
`Loading Steam API...Failed to init SDL priority manager: SDL not found
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed

 Update state (0x5) validating, progress: 94.61 (4540115843 / 4798520693)
 Update state (0x5) validating, progress: 98.22 (4712914273 / 4798520693)
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed
 Update state (0x61) downloading, progress: 99.70 (6309888 / 6328843)`

& this:
`chmod: cannot access '/steamcmd/rust/CSharpCompiler.x86_x64': No such file or directory
chmod: changing permissions of '/dev/null': Operation not permitted
Starting web server..
Log rotation disabled!
Starting Rust..
Found path: /steamcmd/rust/RustDedicated
Unable to open log file, exiting.
Exiting..`

**Comment by Dids** [comment]
Permission issues have been fixed in the latest version.

**Comment by Syntactical01** [comment]
I am still having this issue. I just pulled your image to today, ran it, and got the above error on Windows 10. Docker runs fine and volume is mounted properly.
